- repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
          name: isort (python)
            - id: isort
              name: isort (cython)
              types: [cython]
            - id: isort
              name: isort (pyi)
              types: [pyi]