# Generated by Django 3.2 on 2021-04-21 12:25

from django.db import migrations
from datetime import datetime, timedelta


def add_to_data_base(apps, schema_editor):
    Student = apps.get_model("my_project", "Student")
    Teacher = apps.get_model("my_project", "Teacher")
    Homework = apps.get_model("my_project", "Homework")
    HomeworkResult = apps.get_model("my_project", "HomeworkResult")

    student = Student(last_name="Sokolov", first_name="Lev")
    teacher = Teacher(last_name="Shadrin", first_name="Daniil")
    homework = Homework(
        text="Learn Python", deadline=timedelta(days=3), created=datetime.now()
    )
    homework_result = HomeworkResult(
        homework=homework,
        solution="I have done this hw.",
        author=student,
        created=datetime.now(),
    )

    student.save()
    teacher.save()
    homework.save()
    homework_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_to_data_base)
    ]
